### ISSUE TITLE
Why does running the minimal_system_quick_test modify config/daqsystemtest/ccm.data.xml?

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/daqsystemtest#114]
It seems like it would be nice if integtests do not modify code in locally-cloned repos...

**Comment by eflumerf** [comment]
I've noticed this...I think there's a problem with includes not being updated when files are consolidated into the integtest working directory.

**Comment by eflumerf** [comment]
Resolved by https://github.com/DUNE-DAQ/daqconf/pull/505 and https://github.com/DUNE-DAQ/integrationtest/pull/80
